Form scheduling/budget
Gabrielfernandes7/frontend-consurural pull request #4
Opened 2023-10-30 19:30 UTC by Gabrielfernandes7

2023-10-30 20:58 UTC, lincolnzera1 commented on frontend-consurural/src/index.css
> +  font-size: 50px;
Preferir usar REM no lugar de PX

2023-10-30 21:20 UTC, lincolnzera1 requested changes
Revisão de código

2023-10-30 21:20 UTC, lincolnzera1 commented on frontend-consurural/README.md
> +## Depoimentos
Recomendações e depoimentos estão em falta?

2023-10-30 21:20 UTC, lincolnzera1 commented on frontend-consurural/src/components/SchedulingForm/SchedulingForm.css
> +    font-size: 18px;
Dar preferência a usar REM no lugar de PX no font-size

2023-10-30 21:20 UTC, lincolnzera1 commented on frontend-consurural/src/main.tsx
>    <React.StrictMode>
Pesquisar na internet se o StrictMode é necessário após o fim do desenvolvimento.

2023-10-30 21:20 UTC, lincolnzera1 commented on frontend-consurural/src/components/SchedulingForm/forms/AgriculturalProjectsForm.tsx
> +                /> <br />
Evitar usar tantas tags <br />. No caso bastaria 1 linha de margin bot (css) para os inputs desse formulario.

2023-10-30 21:20 UTC, lincolnzera1 commented on frontend-consurural/src/components/SchedulingForm/forms/ConsultanciesForm.tsx
> +                /> <br />
Revisar o uso exagerado da tab de quebra de linha, como mencionado anteriormente.

2023-10-30 21:55 UTC, Gabrielfernandes7 commented on frontend-consurural/README.md
> +## Depoimentos
Outra task irão ter as duas (Recomendações e depoimentos)

2023-11-03 21:38 UTC, lincolnzera1 approved these changes
ok

2023-11-03 21:41 UTC, merged